name: wikiscrolls_frontend

description: "Onboarding/startup pages for WikiScrolls in Flutter"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  http: ^1.2.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#C67C4E"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#C67C4E"
    theme_color: "#C67C4E"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
